-- MySQL Script generated by MySQL Workbench
-- Wed Jun 15 10:19:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoverhuur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autoverhuur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoverhuur` DEFAULT CHARACTER SET utf8 ;
USE `autoverhuur` ;

-- -----------------------------------------------------
-- Table `autoverhuur`.`tf2class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoverhuur`.`tf2class` ;

CREATE TABLE IF NOT EXISTS `autoverhuur`.`tf2class` (
  `classname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`classname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoverhuur`.`Primaryweapons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoverhuur`.`Primaryweapons` ;

CREATE TABLE IF NOT EXISTS `autoverhuur`.`Primaryweapons` (
  `primname` VARCHAR(45) NOT NULL,
  `weapontype` VARCHAR(45) NULL,
  `image` VARCHAR(500) NULL,
  `tf2class_classname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`primname`, `tf2class_classname`),
  INDEX `fk_Primaryweapons_tf2class1_idx` (`tf2class_classname` ASC) VISIBLE,
  CONSTRAINT `fk_Primaryweapons_tf2class1`
    FOREIGN KEY (`tf2class_classname`)
    REFERENCES `autoverhuur`.`tf2class` (`classname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoverhuur`.`Secondaryweapons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoverhuur`.`Secondaryweapons` ;

CREATE TABLE IF NOT EXISTS `autoverhuur`.`Secondaryweapons` (
  `secname` VARCHAR(45) NOT NULL,
  `weapontype` VARCHAR(45) NULL,
  `image` VARCHAR(500) NULL,
  `tf2class_classname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`secname`, `tf2class_classname`),
  INDEX `fk_Secondaryweapons_tf2class1_idx` (`tf2class_classname` ASC) VISIBLE,
  CONSTRAINT `fk_Secondaryweapons_tf2class1`
    FOREIGN KEY (`tf2class_classname`)
    REFERENCES `autoverhuur`.`tf2class` (`classname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoverhuur`.`Meleeweapons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoverhuur`.`Meleeweapons` ;

CREATE TABLE IF NOT EXISTS `autoverhuur`.`Meleeweapons` (
  `melname` VARCHAR(45) NOT NULL,
  `weapontype` VARCHAR(45) NULL,
  `image` VARCHAR(500) NULL,
  `tf2class_classname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`melname`, `tf2class_classname`),
  INDEX `fk_Meleeweapons_tf2class1_idx` (`tf2class_classname` ASC) VISIBLE,
  CONSTRAINT `fk_Meleeweapons_tf2class1`
    FOREIGN KEY (`tf2class_classname`)
    REFERENCES `autoverhuur`.`tf2class` (`classname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoverhuur`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoverhuur`.`Users` ;

CREATE TABLE IF NOT EXISTS `autoverhuur`.`Users` (
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(50) NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
